### PR TITLE
Added Index Page for Courses, fixed 500 error

### LINKED ISSUE #13: #2 | F2 | Implement Course Index Page | PRIORITY
- [ ] On the course index page, there is a button to take you to the Course Create page.
- [ ] The course index page has a table of all the courses 
- [ ] The course table has a delete button that allows you to delete a course
- [ ] The course table has an edit button that either takes you to a working edit page, or a placeholder page that says "edit coming soon"

### PR DESCRIPTION
**Pull request by Joseph-Foster**
Implemented Index Page for courses with storybook and tests. 

I changed every single instance of start or end to startDate and endDate to fix the 500 error caused by the end keyword.

I also fixed some bugs where the edit and delete was not communicating correctly with the backend.

Screenshot:
image

Storybook link: https://ucsb-cs156-f23.github.io/proj-organic-f23-6pm-1/prs/62/storybook/?path=/story/components-jobs-jobstable--emptytable

Deployment link: https://organic-joseph-foster-dev.dokku-05.cs.ucsb.edu/

Closes #13

### CODE REVIEW

**Review by ErwanDev — APPROVED** [review]
LGTM

**Review by Dagin-Gregory — APPROVED** [review]
Looks good, works locally (and on dokku deployment!!!!!)

**Review by pconrad — APPROVED** [review]
LGTM

**Comment by pconrad** [comment]
20 because this both adds a significant new page (10 points) and fixes the dokku backend thing (10 pts)

**Pull request merged**
