### PR TITLE
Ensure Roles Update Correctly using Interceptors

### LINKED ISSUE #12: #3 | B1 | Show user roles in profile debugging information | PRIORITY
When you toggle the role using the Swagger endpoint, the roles `ROLE_ADMIN` and `ROLE_INSTRUCTOR` show up (or not) on the user profile in the debugging information under roles and in the rolesList as shown below (the example only shows `ROLE_ADMIN` appearing.)

image

### LINKED ISSUE #24: #3 | B1 | Ensure that roles update properly using interceptors | PRIORITY
The code from these files (the interceptors) is adapted for proj-organic and added to the project.  These files help to ensure that roles are updated properly: <https://github.com/ucsb-cs156-s23/proj-gauchoride-s23-5pm-2/tree/main/src/main/java/edu/ucsb/cs156/gauchoride/Interceptors>

### PR DESCRIPTION
**Pull request by Johnsonchan105**
- Added interceptors to ensure admin and instructor roles are updated properly
- Created and implemented tests for interceptors to ensure it is properly working
- Modified MockCurrentUserServiceImpl to use currentUserMock instead of currentUser 
Closes #24 
Closes #12 
Deployed at: https://organic-qa.dokku-05.cs.ucsb.edu

### CODE REVIEW

**Review by pconrad — CHANGES_REQUESTED** [review]
The code LGTM.... but I can't currently test because I can't get the backend toggleAdmin or toggleInstructor to work on swagger on your dokku deployment.

Can you look into that? 

https://organic-qa.dokku-05.cs.ucsb.edu/swagger-ui/index.html

image

I would like to test this change before merging.

**Review by Joseph-Foster — DISMISSED** [review]
LGTM

**Review by Johnsonchan105 — COMMENTED** [review]
Fixed the issue of the 400 error by changing the parameter name in User Controller toggleAdmin and toggleInstructor from "Github Id" to "id".  It should work now when toggling.

**Comment by jakedel** [comment]
> Fixed the issue of the 400 error by changing the parameter name in User Controller toggleAdmin and toggleInstructor from "Github Id" to "id". It should work now when toggling.

Wanted to do a more thorough code review to ensure this is all working.

Review:
Running locally first. Pulled branch, ran npm install, server and frontend started correctly!
Checked my user, admin=true, instructor=false:

Ran toggleInstructor:

Ran toggleAdmin:

Ran toggleAdmin again to check that second toggle works:


Tested on dokku organic-qa too. Looks like it works, checked GET /api/admin/users too and it updated my instructor status to true.


mvn test successful


jacoco looks like full coverage


LGTM :)

**Review by pconrad — DISMISSED** [review]
LGTM but will want to test on dokku

**Comment by chauAlex** [comment]
Working on fixing up the tests right now

**Review by pconrad — APPROVED** [review]
LGTM

**Pull request merged**
