### PR TITLE
Modify DELETE Operation in Courses to work with ROLE_INSTRUCTOR

### LINKED ISSUE #43: #2 | B3 | Modify DELETE Operation in Courses to work with ROLE_INSTRUCTOR
- [x] The backend endpoint DELETE /api/course/staff?id=789 has been modified so that members of the course staff that have ROLE_INSTRUCTOR in the app may delete members of the course staff.

### PR DESCRIPTION
**Pull request by jakedel**
Allow instructors to access the deleteStaff function in CoursesController, but only if they're staff in the same course of the staff member they're trying to remove. Throws a not authorized error similar to the updateCourse function if they aren't.

Closes #43

### CODE REVIEW

**Comment by pconrad** [comment]
So at least one of the jacoco failures here seems to be a legitimate gap in testing:

image

You probably need a test where the user is not an admin, but rather an Instructor (which may require setting up a user that has that role) so that a test gets inside the if.  You'll then probably need two tests: one where the exception isn't thrown, and one where it is.

**Review by pconrad — CHANGES_REQUESTED** [review]
Please see the comment about the jacoco test gap.

**Review by Joseph-Foster — APPROVED** [review]
LGTM

**Review by pconrad — APPROVED** [review]
LGTM!

**Pull request merged**
