### PR TITLE
Erwan Courses Nav Bar

### LINKED ISSUE #17: #2 | F2 | Implement Course App.js Route | PRIORITY
- [x] The navbar has a button for  Courses but it  ONLY for users with ROLE_ADMIN or ROLE_INSTRUCTOR
- [x] When clicked, that button takes you to the Course Index page

### PR DESCRIPTION
**Pull request by ErwanDev**
- The navbar has a button for Courses but it ONLY for users with ROLE_ADMIN or ROLE_INSTRUCTOR
 - When clicked, that button takes you to the Course Index page
 - Tests to make sure Courses nav only shows for admin and instructor users
 - user fixtures for an instructor user.
 
Storybook screenshots: 

Screenshot 2023-11-28 at 3 31 17 PM

Closes #17

### CODE REVIEW

**Comment by ErwanDev** [comment]
Actions will not fully pass until Dagin's PR with the CoursesIndexPage is merged. Full testing coverage and implementation testing was done on a filler index page to ensure the redirect was working.

**Comment by Joseph-Foster** [comment]
I added a placeholder index page and tests so that this will pass the checks.

**Review by Joseph-Foster — APPROVED** [review]
LGTM

**Review by Dagin-Gregory — APPROVED** [review]
LGTM

**Pull request merged**
